kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/cinder
    volume.kubernetes.io/selected-node: node-pvc-database-blog
  name: pvc-database-blog
  namespace: fiap
  labels:
    app: pvc-database-blog-rm340709
    RM: 'RM340709_PVC'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: pvc-database-blog