FROM centos/centos:8.3
MAINTAINER Lucas de Barros
LABEL description="Customzização de imagem feita apartir de apache e centOS"
RUN yum install -y httpd && \
    yum clean all
RUN echo "Hello FIAP RM 340709" > /var/www/html/index.html
EXPOSE 80
CMD ["httpd", "-D", "FOREGROUND"]