apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fiap
resources:
  - pvc/pvc-database.yml
  - secret/database-secret
  - database/deployment-database.yml
  - blog/deployment-blog.yml
  - service/blog-service.yml
  - service/database-service.yml
  - hpa/hpa-blog.yml
  - hpa/hpa-database.yml